version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
  target-branch: dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
